### ISSUE TITLE
Adding Data East 2x16 display support

### ISSUE THREAD

**Issue by tmator** [AmokSolderer/APC#31]
Hello, is it possible to add DE 2x16 display support ?

After reading schemating between Rollergames and DE displays I think they just invert the logicin the segment part.

A simple mask to flip bit on this output should be ok.

**Comment by AmokSolderer** [comment]
Starting with V00.23 there's a new display setting 'Data East 2x16' which supports DE displays having two rows with 16 alphanumerical characters each.
