### ISSUE TITLE
working on pinball data east MPU ?

### ISSUE THREAD

**Issue by theck32** [AmokSolderer/APC#32]
I have a data east Mary shelley's Frankenstein pinball and my MPU board is not functional, is it possible to use your board system to make my pinball work? thank you

**Comment by AmokSolderer** [comment]
No, you can't use the APC for this DE generation as it doesn't support DMDs.

**Comment by JustinRudebaugh** [comment]
Send a message to Chris Hibler http://chrishiblerpinball.com/
